<a href="https://colab.research.google.com/github/AllanGonzales/Matrix-Algebra/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Program to Inverse:

In [2]:
import numpy as np
A= np.array ([[2,3,4],[1,5,6],[8,9,1]])
B= (np.linalg.inv(A))
print(B)

[[ 0.60493827 -0.40740741  0.02469136]
 [-0.58024691  0.37037037  0.09876543]
 [ 0.38271605 -0.07407407 -0.08641975]]


Transpose:

In [3]:
A= np.array ([[2,3,4],[1,5,6],[8,9,1]])
print(A)
B = np.transpose(A)
print(B)


[[2 3 4]
 [1 5 6]
 [8 9 1]]
[[2 1 8]
 [3 5 9]
 [4 6 1]]
